program: SterenchakRobert10.o getdouble.o
	gcc SterenchakRobert10.o getdouble.o -o SterenchakRobert10 -lm

SterenchakRobert10.o: SterenchakRobert10.c getdouble.h
	gcc -c SterenchakRobert10.c

getdouble.o: getdouble.c getdouble.h
	gcc -c getdouble.c

